### ISSUE TITLE
Research connecting Emulator to Hue hub

### ISSUE THREAD

**Issue by bnguyen142** [Codepath-Team-Hyperion/Helios#4]

**Comment by supermancantswim** [comment]
We've implemented an old SDK from Philips Hue last updated 2017.
https://github.com/PhilipsHue/PhilipsHueSDK-Java-MultiPlatform-Android
I painstakingly, updated it to androidx so we can use new features of Android Studio. Seems to be working well and we can move on.

Android Emulator connects to the hub easily. Yay!
